import type { Skill } from './types';

const thin = (value: string | undefined, minimum = 180) => !value || value.trim().length < minimum;
const weak = (value: string | undefined) => !value || /comprehensive understanding and practical application|increasingly important for professional success|modern organizations require|today'?s competitive business environment/i.test(value);
const names = (values: string[] | undefined, fallback: string[]) => values?.length ? values : fallback;
const sentenceList = (values: string[]) => values.map((v) => v.replace(/[-_]/g, ' ')).join(', ');

const categoryLens: Record<string, { focus: string; evidence: string; practice: string }> = {
  communication: { focus: 'clarity, audience judgment, listening, message design, and observable understanding', evidence: 'message quality, stakeholder understanding, response quality, reduced rework, and feedback from the people receiving the communication', practice: 'real conversations, written briefs, presentations, feedback loops, and deliberate review of whether the audience understood and acted' },
  leadership: { focus: 'direction, systems thinking, decision rights, stakeholder alignment, behavior change, and sustained performance', evidence: 'decision quality, adoption, team effectiveness, stakeholder alignment, operating outcomes, and whether improvements persist after the intervention', practice: 'diagnosis, facilitated workshops, change initiatives, retrospectives, coaching, and progressively larger leadership responsibilities' },
  'critical-thinking': { focus: 'problem framing, evidence quality, assumptions, alternatives, trade-offs, and defensible conclusions', evidence: 'quality of reasoning, accuracy, decision outcomes, ability to surface assumptions, and performance against a credible baseline', practice: 'case analysis, decision journals, premortems, root-cause analysis, argument mapping, and post-decision review' },
  collaboration: { focus: 'shared goals, coordination, trust, role clarity, constructive conflict, and reliable handoffs', evidence: 'team outcomes, cycle time, handoff quality, conflict resolution, peer feedback, and clarity of ownership', practice: 'cross-functional projects, facilitation, team retrospectives, shared planning, and explicit working agreements' },
  'personal-effectiveness': { focus: 'self-management, prioritization, consistency, judgment, energy, and reliable execution', evidence: 'follow-through, quality, timeliness, workload sustainability, reduced avoidable errors, and feedback from collaborators', practice: 'small repeatable routines, reflection, time-boxed experiments, feedback, and tracking behavior rather than intention' },
  'business-strategy': { focus: 'strategic choices, market context, resource allocation, competitive advantage, execution, and measurable outcomes', evidence: 'quality of strategic choices, leading indicators, business outcomes, resource efficiency, and learning against explicit assumptions', practice: 'strategy cases, market analysis, scenario planning, business reviews, decision memos, and ownership of measurable initiatives' },
  'sales-marketing': { focus: 'customer insight, positioning, persuasion, channel economics, experimentation, and revenue impact', evidence: 'conversion, pipeline quality, retention, acquisition efficiency, message resonance, and controlled experiment results', practice: 'customer interviews, campaign experiments, sales calls, copy testing, funnel analysis, and post-campaign review' },
  'finance-operations': { focus: 'process reliability, economics, controls, forecasting, resource use, and operational trade-offs', evidence: 'cost, quality, cycle time, forecast accuracy, control effectiveness, throughput, and service levels', practice: 'process mapping, reconciliations, forecasts, operational reviews, root-cause analysis, and measurable improvement projects' },
  'human-resources': { focus: 'people systems, workforce evidence, fairness, capability, employee experience, and organizational outcomes', evidence: 'quality of people decisions, adoption, capability growth, retention, employee experience, fairness indicators, and business outcomes', practice: 'workforce cases, interviews, diagnostics, policy review, facilitated interventions, and measurement before and after changes' },
  'customer-success': { focus: 'customer outcomes, adoption, relationship quality, risk detection, value realization, and retention', evidence: 'adoption, retention, expansion, time-to-value, customer health, satisfaction, and documented outcome realization', practice: 'customer conversations, success plans, account reviews, risk diagnosis, onboarding improvement, and outcome tracking' },
  'digital-literacy': { focus: 'tool judgment, information quality, safe digital behavior, workflow design, and effective use of technology', evidence: 'task quality, speed, security, information accuracy, reduced manual effort, and appropriate tool selection', practice: 'hands-on tool use, workflow experiments, security checks, source verification, and comparing manual and digital approaches' },
  'content-media': { focus: 'audience insight, narrative, craft, distribution, editorial judgment, and measurable audience response', evidence: 'clarity, retention, engagement quality, conversion, editorial quality, and performance against the content objective', practice: 'publishing, editing, audience research, format experiments, critiques, and reviewing performance data' },
  'design-ux': { focus: 'user needs, problem framing, interaction quality, accessibility, prototyping, and evidence-led iteration', evidence: 'task success, usability, accessibility, user feedback, reduced friction, and measurable improvement after iteration', practice: 'user interviews, prototypes, usability tests, design critiques, accessibility checks, and iterative redesign' },
  technical: { focus: 'correctness, system behavior, reliability, maintainability, security, and engineering trade-offs', evidence: 'working artifacts, tests, reliability, performance, code or system quality, incident reduction, and peer review', practice: 'building real systems, debugging, code review, labs, benchmarks, documentation, and progressively harder implementation projects' },
  'analytics-research': { focus: 'question design, data quality, methods, uncertainty, interpretation, and reproducibility', evidence: 'methodological fit, data quality, reproducibility, predictive or explanatory performance, and decision usefulness', practice: 'real datasets, research questions, analysis notebooks, peer review, replication, and comparing conclusions with outcomes' },
  'remote-work': { focus: 'asynchronous clarity, autonomy, coordination, documentation, trust, and distributed team effectiveness', evidence: 'handoff quality, response clarity, meeting load, delivery reliability, documentation usefulness, and distributed-team feedback', practice: 'async-first projects, written updates, remote facilitation, documentation, explicit norms, and timezone-aware coordination' },
  entrepreneurship: { focus: 'customer problems, experimentation, economics, resource constraints, selling, and learning speed', evidence: 'customer evidence, revenue or adoption, experiment quality, runway efficiency, retention, and speed of validated learning', practice: 'customer discovery, small launches, pricing tests, sales, prototypes, unit-economics review, and founder retrospectives' },
  'freelance-gig': { focus: 'client outcomes, scoping, delivery, reputation, pricing, communication, and independent operations', evidence: 'client results, repeat work, referrals, margin, delivery reliability, scope control, and portfolio quality', practice: 'small client projects, proposals, scoped deliverables, retrospectives, portfolio building, and pricing experiments' },
  'ai-era': { focus: 'task decomposition, model capability and limits, evaluation, human oversight, workflow integration, and responsible use', evidence: 'task success, evaluation results, error rates, review effort, cost, safety, traceability, and improvement over a non-AI baseline', practice: 'real workflows, controlled evaluations, prompt and tool experiments, failure analysis, human review, and documented before-and-after comparisons' },
  'future-resistant': { focus: 'adaptability, human judgment, systems awareness, learning agility, relationship value, and work that remains difficult to automate', evidence: 'transfer across contexts, decision quality, learning speed, stakeholder trust, novel problem solving, and resilience under change', practice: 'cross-domain projects, reflection, scenario exercises, stretch assignments, feedback, and deliberate transfer of the skill into unfamiliar contexts' },
};

function baseCompletion(skill: Skill): Skill {
  const lens = categoryLens[skill.category] ?? categoryLens['personal-effectiveness'];
  const contexts = names(skill.professionalContexts, ['projects', 'team decisions', 'day-to-day execution']);
  const careers = names(skill.careers, ['specialist', 'managerial', 'client-facing', 'cross-functional']);
  const industries = names(skill.industries, ['professional services', 'technology', 'public and nonprofit organizations']);
  const tools = names(skill.tools, ['role-appropriate planning, analysis, and collaboration tools']);
  const beginner = names(skill.beginnerActions, [`Learn the core concepts behind ${skill.name}`, `Observe strong examples of ${skill.name} in practice`]);
  const intermediate = names(skill.intermediateActions, [`Apply ${skill.name} to a real project`, `Ask for feedback on outcomes and process`]);
  const advanced = names(skill.advancedActions, [`Lead higher-stakes ${skill.name} work`, `Teach or standardize effective practice`]);
  const mistakes = names(skill.commonMistakes, ['using a technique without diagnosing the situation', 'measuring activity instead of outcomes', 'failing to seek feedback']);

  return {
    ...skill,
    fullDefinition: weak(skill.fullDefinition) ? `${skill.name} is the ability to apply domain knowledge, judgment, and repeatable methods to produce a specific professional outcome rather than simply knowing terminology. In practice, it combines ${lens.focus}. Competence means diagnosing the situation, choosing an approach that fits the constraints, executing it, checking the result, and adapting when evidence shows the approach is not working. Strong practitioners can explain both what they did and why the method was appropriate.` : skill.fullDefinition,
    whyItMatters: weak(skill.whyItMatters) ? `${skill.name} matters because organizations do not benefit from knowledge that cannot be translated into reliable action. The skill affects the quality and speed of work, the ability to coordinate with other people, and the likelihood that decisions produce the intended result. Its value is highest when the practitioner can connect the skill to an explicit business, customer, team, or professional outcome and can show evidence of improvement rather than merely claiming familiarity.` : skill.whyItMatters,
    modernRelevance: thin(skill.modernRelevance, 150) ? `Modern work makes ${skill.name} more demanding because teams operate across functions, tools, locations, and rapidly changing constraints. AI and automation can accelerate parts of the workflow, but they also increase the need to define the problem correctly, verify outputs, exercise judgment, and integrate technology into a wider human system. Current proficiency therefore includes both the underlying discipline and the ability to use new tools without outsourcing accountability.` : skill.modernRelevance,
    whereItShowsUp: thin(skill.whereItShowsUp) ? `${skill.name} appears in ${sentenceList(contexts)}. It is especially visible when a professional must turn an ambiguous objective into a concrete plan, coordinate with other people, make trade-offs, and demonstrate that the result improved. The exact task varies by role, but the common pattern is diagnosis → choice of method → execution → feedback → adjustment.` : skill.whereItShowsUp,
    careerApplications: thin(skill.careerApplications) ? `Across ${sentenceList(careers.slice(0, 6))} roles, ${skill.name} changes with scope. Early-career practitioners use it to execute defined work reliably. More experienced practitioners use it to diagnose less-structured problems, coordinate stakeholders, and improve systems. At leadership level, the skill becomes less about personally performing every task and more about setting standards, designing conditions for good execution, reviewing evidence, and making trade-offs across competing priorities.` : skill.careerApplications,
    industryVariations: thin(skill.industryVariations) ? `The core principles of ${skill.name} transfer across industries, but constraints differ. In ${sentenceList(industries.slice(0, 6))}, practitioners may face different regulation, risk tolerance, customer expectations, operating rhythms, and technology. Mastery therefore means preserving the underlying objective while adapting language, evidence, tools, governance, and pace to the environment.` : skill.industryVariations,
    skillInAction: thin(skill.skillInAction) ? `Strong ${skill.name} is observable. A capable practitioner clarifies the outcome, gathers enough evidence to understand the situation, selects a proportionate method, communicates assumptions, executes with appropriate tools such as ${sentenceList(tools.slice(0, 5))}, and checks whether the result actually improved. They distinguish activity from impact, surface uncertainty instead of hiding it, and change course when feedback contradicts the original plan.` : skill.skillInAction,
    realWorldScenarios: skill.realWorldScenarios?.length ? skill.realWorldScenarios : [
      `A team has an important outcome but no shared approach. You use ${skill.name} to clarify the objective, identify constraints, agree on a method, and define how success will be measured.`,
      `A familiar process is producing inconsistent results. You apply ${skill.name} to diagnose the failure points, test an improvement, and compare the result with the previous baseline.`,
      `Stakeholders disagree about what good execution looks like. You use evidence, explicit trade-offs, and ${skill.name} principles to create a workable decision and review point.`,
    ],
    coreSubskills: skill.coreSubskills?.length ? skill.coreSubskills : [
      `Problem framing for ${skill.name}`,
      'Evidence gathering and diagnosis',
      'Method and tool selection',
      'Stakeholder communication and coordination',
      'Execution under real constraints',
      'Measurement, feedback, and iteration',
    ],
    developmentMethods: thin(skill.developmentMethods) ? `Develop ${skill.name} through a progression from observation to controlled practice to ownership. Start with: ${sentenceList(beginner.slice(0, 3))}. Then move to: ${sentenceList(intermediate.slice(0, 3))}. Advanced development should include: ${sentenceList(advanced.slice(0, 3))}. Keep a short decision-and-feedback log so practice produces evidence about what works rather than simply more repetition.` : skill.developmentMethods,
    practiceOpportunities: thin(skill.practiceOpportunities) ? `Use live work whenever the downside is manageable: volunteer for a project, improvement effort, analysis, presentation, customer problem, or cross-functional task where ${skill.name} affects a visible outcome. Define a baseline before acting, ask a more experienced person to review the approach, and capture the result as a small portfolio case. Simulations and case studies are useful when real-world practice would carry too much risk.` : skill.practiceOpportunities,
    howEmployersEvaluate: thin(skill.howEmployersEvaluate) ? `Employers rarely evaluate ${skill.name} from a claim alone. They look for specific examples, the difficulty of the situation, the candidate's reasoning, artifacts or outputs, feedback from stakeholders, and measurable results. In interviews, strong evidence explains the starting condition, choices made, trade-offs, result, and what changed afterward. On the job, evaluation should focus on ${lens.evidence}.` : skill.howEmployersEvaluate,
    signalsOfMastery: skill.signalsOfMastery?.length ? skill.signalsOfMastery : [
      `Can explain ${skill.name} clearly without relying on jargon`,
      'Chooses methods based on context rather than habit',
      'Produces evidence of outcomes, not just completed activity',
      'Anticipates common failure modes and builds checks around them',
      'Adapts the skill successfully to unfamiliar situations',
      'Can coach another person and explain the reasoning behind the approach',
    ],
    careerImpact: thin(skill.careerImpact) ? `${skill.name} becomes more career-relevant as work becomes less prescribed. Demonstrated proficiency can expand the scope of projects a person is trusted to own, strengthen evidence for promotion or role changes, and make adjacent career moves easier when the underlying capability transfers. The strongest career signal is a set of concrete examples showing progressively harder problems, better judgment, and measurable outcomes.` : skill.careerImpact,
    evidenceSummary: thin(skill.evidenceSummary) ? `For this guide, treat evidence in layers: established principles from the discipline, current professional practice, and results from the learner's own context. Avoid treating popularity, tool adoption, or a single framework as proof of effectiveness. When practicing ${skill.name}, compare outcomes with a baseline, gather stakeholder feedback where relevant, document assumptions, and look for repeatable improvement. Appropriate evidence includes ${lens.evidence}.` : skill.evidenceSummary,
    howToPractice: weak(skill.howToPractice) ? `Practice ${skill.name} through ${lens.practice}. Choose one real outcome, define what better would look like, perform the work, collect feedback, and repeat with one deliberate change. Increase complexity only after you can produce a reliable result at the current level.` : skill.howToPractice,
    howToMeasureProgress: weak(skill.howToMeasureProgress) ? `Measure progress using ${lens.evidence}. Keep at least one outcome metric and one quality or process metric. Compare against your own baseline, not vague impressions, and periodically ask a knowledgeable peer or stakeholder to review both the result and your reasoning.` : skill.howToMeasureProgress,
    commonMistakes: mistakes,
  };
}

function organizationalDevelopment(skill: Skill): Skill {
  if (skill.slug !== 'organizational-development' && skill.name.toLowerCase() !== 'organizational development') return skill;
  return {
    ...skill,
    shortDefinition: 'A planned, evidence-informed, systems approach to improving organizational effectiveness by changing how people, culture, capabilities, structures, relationships, and ways of working interact.',
    fullDefinition: 'Organizational Development (OD) is a planned and systematic discipline for improving sustained organizational performance through people and the wider organizational system. It is broader than running a change project and different from organization design alone. OD uses behavioral science, systems thinking, diagnosis, action research, facilitation, and iterative intervention to understand how culture, capability, values, relationships, structures, processes, incentives, and technology combine to shape behavior and performance. The practitioner studies the current state, develops hypotheses about what is helping or constraining performance, involves affected people in diagnosis and change, selects interventions that fit the evidence, and evaluates whether the system actually improved.',
    whyItMatters: 'Organizations routinely face strategy shifts, AI adoption, restructuring, growth, mergers, workforce capability gaps, culture problems, and new operating models. Treating these as communication exercises or org-chart changes misses the system around the problem. OD helps leaders connect strategy to the conditions people work within, identify root causes instead of symptoms, and design changes that can be adopted and sustained. It is particularly valuable when performance depends on several interacting factors—roles, decision rights, skills, incentives, leadership behavior, workflows, culture, and technology—rather than one isolated fix.',
    modernRelevance: 'OD has become more important as organizations combine hybrid work, skills-based workforce planning, AI-enabled workflows, rapid restructuring, and continuous transformation. Modern OD practitioners must be able to diagnose both the human and operating system: how work is designed, where decisions sit, what capabilities are missing, how technology changes roles, which behaviors the culture rewards, and whether change is producing measurable value. AI can support analysis, synthesis, scenario generation, and listening at scale, but responsibility for ethical judgment, participation, power dynamics, organizational context, and intervention design remains human.',
    whereItShowsUp: 'OD shows up in culture and behavior change, post-merger integration, operating-model shifts, leadership-team effectiveness, workforce capability building, employee experience redesign, restructuring, hybrid-work redesign, succession and talent systems, cross-functional coordination problems, strategic workforce planning, AI adoption, and organization-wide transformation. A typical engagement moves from contracting and defining the business issue to diagnosis, sense-making, intervention design, implementation, evaluation, and reinforcement.',
    careerApplications: 'OD specialists, HR business partners, people leaders, change consultants, transformation leaders, learning leaders, and executives use OD at different levels. Practitioners may run interviews, focus groups, surveys, observations, network or process mapping, workshops, and action-research cycles. Managers use OD thinking to diagnose team systems rather than blame individuals. Senior leaders use it to align strategy, operating model, culture, capability, governance, and measures. Consultants must also contract carefully with sponsors, protect the integrity of diagnostic evidence, and create enough participation that the organization can own the change after the consultant leaves.',
    industryVariations: 'OD principles transfer across sectors, but intervention design changes with context. Healthcare places heavier weight on clinical governance, professional identities, safety, and multidisciplinary coordination. Technology organizations may emphasize product operating models, rapid growth, distributed teams, and AI-enabled work. Financial services add regulatory controls and risk governance. Government and nonprofit settings often involve public accountability, complex stakeholder systems, constrained resources, and mission outcomes. Manufacturing may focus more heavily on operating processes, safety, frontline systems, and continuous improvement. The practitioner should adapt methods without abandoning diagnosis, participation, evidence, and evaluation.',
    skillInAction: 'Strong OD begins with a business or organizational outcome, not a fashionable intervention. The practitioner contracts with sponsors, defines the system boundary, gathers evidence from multiple sources, separates symptoms from plausible causes, and feeds findings back in a way that enables collective sense-making. They select interventions at the right level—individual, team, intergroup, process, structure, capability, culture, or whole system—then define adoption and performance measures before implementation. They watch for unintended consequences, power dynamics, local workarounds, and change fatigue, and they iterate rather than assuming the first design is correct.',
    coreSubskills: ['Systems thinking and system boundary definition','OD contracting and stakeholder alignment','Organizational diagnosis and hypothesis building','Qualitative interviewing, observation, focus groups, surveys, and mapping','Action research and iterative intervention','Facilitation and participative change','Culture and behavior analysis','Organization design and work-design literacy','Change readiness, adoption, and reinforcement','Capability and strategic workforce analysis','Evaluation, measurement, and learning loops','Ethics, power, inclusion, and psychological safety in change'],
    realWorldScenarios: [
      'A fast-growing company has added layers of management, but decisions are slower and teams blame one another. Diagnose decision rights, interfaces, incentives, meeting load, role clarity, and leadership behavior before recommending a structural change.',
      'An organization deploys AI tools but adoption stalls. Map affected work, identify capability and trust gaps, clarify human accountability, redesign workflows, involve employees in testing, and measure both adoption and business outcomes.',
      'Two organizations merge and leadership wants a culture workshop. First diagnose differences in operating norms, identity, incentives, decision processes, customer commitments, and leadership signals; then design targeted integration interventions rather than treating culture as slogans.',
      'Employee engagement falls after repeated transformations. Use listening data, interviews, workload evidence, leadership behavior, and change history to distinguish change fatigue from unclear direction, poor sequencing, low participation, or broken reinforcement systems.',
      'A strategy requires more cross-functional innovation, but performance management rewards local optimization. Redesign goals, forums, decision rights, team interfaces, and leadership routines so the organizational system reinforces the desired behavior.'
    ],
    beginnerActions: ['Learn the distinction between organization development, organization design, and change management','Study systems thinking, action research, appreciative inquiry, and core change concepts','Practice turning a vague people problem into a testable organizational diagnosis','Observe or assist with interviews, focus groups, surveys, retrospectives, and facilitated workshops'],
    intermediateActions: ['Lead a bounded diagnostic using multiple evidence sources','Contract with a sponsor on outcomes, scope, roles, confidentiality, and measures','Design and facilitate an intervention tied to a diagnosed cause','Measure adoption and performance before and after an intervention','Run an action-research cycle and revise the intervention from evidence'],
    advancedActions: ['Lead enterprise-level OD strategy across multiple interacting systems','Integrate organization design, culture, capability, technology, and workforce planning','Advise executives on transformation choices, power dynamics, and unintended consequences','Build internal OD capability so teams can diagnose and improve their own systems','Create governance and evaluation practices for a portfolio of organizational interventions'],
    developmentMethods: 'Build OD capability through supervised diagnosis and facilitation, not theory alone. Start with a bounded team or process problem. Write a contracting statement, define the system and desired outcome, collect at least two forms of evidence, develop competing hypotheses, and feed the diagnosis back to stakeholders. Design one proportionate intervention and establish measures before launch. After implementation, conduct a review of intended outcomes, adoption, side effects, and what the organization learned. Progress to larger systems only as your ability to manage ambiguity, participation, ethics, and measurement improves.',
    practiceOpportunities: 'Useful practice includes team-effectiveness reviews, onboarding redesign, cross-functional retrospectives, capability-gap analysis, employee-listening projects, process and decision-right mapping, post-project reviews, change-readiness assessments, communities of practice, and volunteering to facilitate a real improvement effort. Build a portfolio that shows the diagnosis, evidence, intervention logic, stakeholder involvement, measures, results, and lessons—not confidential employee data.',
    howEmployersEvaluate: 'Employers look for evidence that an OD practitioner can diagnose before prescribing, work credibly with leaders and employees, facilitate difficult conversations, connect people issues to strategy and performance, use qualitative and quantitative evidence, design interventions at the right system level, and evaluate whether change stuck. Interviews often probe ambiguous transformation cases. Strong candidates can explain their contracting choices, evidence, hypotheses, intervention logic, resistance or power dynamics, measures, outcomes, and what they would change next time.',
    signalsOfMastery: ['Frames organizational problems as systems rather than immediately blaming people','Uses multiple evidence sources and distinguishes symptoms from causes','Can explain why a chosen intervention fits the diagnosis','Creates participation without surrendering decision clarity','Connects culture and behavior to structures, processes, incentives, and leadership signals','Defines adoption and performance measures before implementation','Recognizes power, ethics, confidentiality, and unintended consequences','Leaves the organization with stronger internal capability, not dependency on the practitioner'],
    howToPractice: 'Choose a real, bounded organizational problem and run a small action-research cycle: contract on the outcome and scope; gather evidence through interviews, observation, surveys, or process data; form and test hypotheses; feed the diagnosis back; co-design a targeted intervention; define adoption and performance measures; implement; then review results and unintended effects. Repeat with progressively larger and more politically complex systems.',
    howToMeasureProgress: 'Track the quality of diagnosis, stakeholder trust, intervention adoption, and organizational outcomes. Depending on the problem, useful measures include decision speed, cycle time, rework, customer outcomes, capability measures, cross-team handoff quality, retention, engagement, safety, or productivity. Pair outcome metrics with qualitative evidence so a numerical change is not mistaken for proof of causation. Review whether improvements persist after active change support ends.',
    commonMistakes: ['Starting with a favorite intervention before diagnosing the system','Treating culture as slogans instead of patterns reinforced by systems and leadership behavior','Confusing organization development with organization design or communication planning','Collecting employee input without closing the feedback loop','Using a survey as the diagnosis rather than one evidence source','Ignoring power, incentives, identity, workload, or informal networks','Measuring activity and adoption but not organizational outcomes','Launching change without reinforcement in goals, governance, processes, and leadership routines'],
    evidenceSummary: 'Current professional guidance from CIPD describes organization development as a planned and systematic approach to sustained organizational performance through people, using a systems perspective on culture, capability, values, relationships, and behavior. CIPD’s profession standards distinguish organization design—operating models, structures, systems, processes, and metrics—from organization development’s behavioral-science focus, while treating them as complementary. SHRM similarly emphasizes aligning structure, processes, people, technology, decision rights, coordination, and change adoption with strategy. For practice, use these principles as a framework and evaluate interventions against local evidence rather than assuming a named model guarantees success.',
    scholarlyNotes: ['Systems thinking: examine interactions among structure, process, people, technology, incentives, culture, and environment rather than isolating one variable.','Action research: treat diagnosis, intervention, observation, and learning as an iterative cycle with participant involvement.','Appreciative inquiry: useful when inquiry into strengths and desired possibilities is more appropriate than deficit-only diagnosis.','Change frameworks such as Kotter or ADKAR can structure parts of implementation, but should not replace diagnosis or be treated as universal causal laws.'],
    lastUpdated: '2026-09-08'
  };
}

export function completeSkillGuide(input: Skill): Skill {
  return organizationalDevelopment(baseCompletion(input));
}
