-- Modern Skill Lab Growth Console
-- Adds newsletter capture, anonymous content analytics, featured-skill controls,
-- ad placement controls, and an admin flag for account management.

ALTER TABLE public.profiles
  ADD COLUMN IF NOT EXISTS is_admin BOOLEAN NOT NULL DEFAULT FALSE;

CREATE OR REPLACE FUNCTION public.is_admin()
RETURNS BOOLEAN
LANGUAGE sql
STABLE
SECURITY DEFINER
SET search_path = public
AS $$
  SELECT COALESCE(
    (SELECT p.is_admin FROM public.profiles p WHERE p.id = auth.uid()),
    FALSE
  );
$$;


-- Keep the admin flag server-managed. The initial schema allows members to update
-- their own profile, so narrow that privilege before introducing is_admin.
REVOKE UPDATE ON public.profiles FROM authenticated;
GRANT UPDATE (name, career_interests, selected_industries, saved_skills, saved_careers, followed_categories, preferences, updated_at)
  ON public.profiles TO authenticated;

-- Canonical saved-skill relation used by the current dashboard/save button.
-- A compatibility trigger keeps profiles.saved_skills in sync for older code paths.
CREATE TABLE IF NOT EXISTS public.saved_skills (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  user_id UUID NOT NULL REFERENCES public.profiles(id) ON DELETE CASCADE,
  skill_slug TEXT NOT NULL,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  UNIQUE(user_id, skill_slug)
);

-- Preserve any skills that were previously stored only in profiles.saved_skills.
INSERT INTO public.saved_skills (user_id, skill_slug)
SELECT p.id, skill_slug
FROM public.profiles p
CROSS JOIN LATERAL unnest(COALESCE(p.saved_skills, '{}'::TEXT[])) AS skill_slug
ON CONFLICT (user_id, skill_slug) DO NOTHING;

ALTER TABLE public.saved_skills ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS "Users manage own saved skills" ON public.saved_skills;
CREATE POLICY "Users manage own saved skills" ON public.saved_skills
  FOR ALL TO authenticated
  USING (auth.uid() = user_id)
  WITH CHECK (auth.uid() = user_id);

DROP POLICY IF EXISTS "Admins view saved skills" ON public.saved_skills;
CREATE POLICY "Admins view saved skills" ON public.saved_skills
  FOR SELECT TO authenticated USING (public.is_admin());

CREATE OR REPLACE FUNCTION public.sync_profile_saved_skills()
RETURNS TRIGGER
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public
AS $$
DECLARE
  target_user UUID;
BEGIN
  IF TG_OP = 'DELETE' THEN
    target_user := OLD.user_id;
  ELSE
    target_user := NEW.user_id;
  END IF;

  UPDATE public.profiles
  SET saved_skills = COALESCE(
    (SELECT array_agg(s.skill_slug ORDER BY s.created_at) FROM public.saved_skills s WHERE s.user_id = target_user),
    '{}'::TEXT[]
  )
  WHERE id = target_user;

  IF TG_OP = 'DELETE' THEN
    RETURN OLD;
  END IF;
  RETURN NEW;
END;
$$;

DROP TRIGGER IF EXISTS sync_profile_saved_skills_after_change ON public.saved_skills;
CREATE TRIGGER sync_profile_saved_skills_after_change
  AFTER INSERT OR DELETE ON public.saved_skills
  FOR EACH ROW EXECUTE FUNCTION public.sync_profile_saved_skills();

CREATE INDEX IF NOT EXISTS idx_saved_skills_user_id ON public.saved_skills(user_id);
CREATE INDEX IF NOT EXISTS idx_saved_skills_slug ON public.saved_skills(skill_slug);

CREATE TABLE IF NOT EXISTS public.newsletter_subscribers (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  email TEXT NOT NULL UNIQUE,
  source TEXT NOT NULL DEFAULT 'website',
  status TEXT NOT NULL DEFAULT 'subscribed' CHECK (status IN ('subscribed', 'unsubscribed')),
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);


CREATE OR REPLACE FUNCTION public.subscribe_newsletter(p_email TEXT, p_source TEXT DEFAULT 'website')
RETURNS VOID
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public
AS $$
BEGIN
  IF p_email IS NULL OR length(trim(p_email)) > 254 OR trim(p_email) !~* '^[^@\s]+@[^@\s]+\.[^@\s]+$' THEN
    RAISE EXCEPTION 'invalid email';
  END IF;

  INSERT INTO public.newsletter_subscribers (email, source, status)
  VALUES (lower(trim(p_email)), left(COALESCE(NULLIF(trim(p_source), ''), 'website'), 80), 'subscribed')
  ON CONFLICT (email) DO UPDATE
    SET status = 'subscribed',
        source = EXCLUDED.source,
        updated_at = NOW();
END;
$$;

GRANT EXECUTE ON FUNCTION public.subscribe_newsletter(TEXT, TEXT) TO anon, authenticated;

CREATE TABLE IF NOT EXISTS public.content_events (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  event_type TEXT NOT NULL CHECK (event_type IN ('page_view', 'skill_view', 'career_view', 'blog_view', 'cta_click')),
  item_type TEXT CHECK (item_type IN ('skill', 'career', 'blog', 'page')),
  item_slug TEXT,
  path TEXT,
  referrer TEXT,
  session_id TEXT,
  user_id UUID REFERENCES auth.users(id) ON DELETE SET NULL,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);


-- Public aggregate only: exposes popularity counts without exposing raw visitor events.
CREATE OR REPLACE FUNCTION public.get_trending_skills(p_days INTEGER DEFAULT 7, p_limit INTEGER DEFAULT 6)
RETURNS TABLE(item_slug TEXT, views BIGINT)
LANGUAGE sql
STABLE
SECURITY DEFINER
SET search_path = public
AS $$
  SELECT e.item_slug, COUNT(*)::BIGINT AS views
  FROM public.content_events e
  WHERE e.event_type = 'skill_view'
    AND e.item_slug IS NOT NULL
    AND e.created_at >= NOW() - make_interval(days => LEAST(GREATEST(p_days, 1), 90))
  GROUP BY e.item_slug
  ORDER BY views DESC, e.item_slug ASC
  LIMIT LEAST(GREATEST(p_limit, 1), 50);
$$;

GRANT EXECUTE ON FUNCTION public.get_trending_skills(INTEGER, INTEGER) TO anon, authenticated;

CREATE TABLE IF NOT EXISTS public.featured_skills (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  skill_slug TEXT NOT NULL,
  feature_type TEXT NOT NULL DEFAULT 'editor' CHECK (feature_type IN ('week', 'month', 'editor')),
  homepage_headline TEXT,
  starts_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  ends_at TIMESTAMPTZ,
  display_order INTEGER NOT NULL DEFAULT 0,
  active BOOLEAN NOT NULL DEFAULT TRUE,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS public.ad_placements (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  placement_key TEXT NOT NULL UNIQUE,
  label TEXT NOT NULL,
  description TEXT,
  enabled BOOLEAN NOT NULL DEFAULT FALSE,
  slot_id TEXT,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS public.site_settings (
  key TEXT PRIMARY KEY,
  value JSONB NOT NULL DEFAULT '{}'::jsonb,
  is_public BOOLEAN NOT NULL DEFAULT FALSE,
  updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

DROP TRIGGER IF EXISTS set_newsletter_subscribers_updated_at ON public.newsletter_subscribers;
CREATE TRIGGER set_newsletter_subscribers_updated_at
  BEFORE UPDATE ON public.newsletter_subscribers
  FOR EACH ROW EXECUTE FUNCTION public.handle_updated_at();

DROP TRIGGER IF EXISTS set_featured_skills_updated_at ON public.featured_skills;
CREATE TRIGGER set_featured_skills_updated_at
  BEFORE UPDATE ON public.featured_skills
  FOR EACH ROW EXECUTE FUNCTION public.handle_updated_at();

DROP TRIGGER IF EXISTS set_ad_placements_updated_at ON public.ad_placements;
CREATE TRIGGER set_ad_placements_updated_at
  BEFORE UPDATE ON public.ad_placements
  FOR EACH ROW EXECUTE FUNCTION public.handle_updated_at();

ALTER TABLE public.newsletter_subscribers ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.content_events ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.featured_skills ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.ad_placements ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.site_settings ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS "Anyone can subscribe" ON public.newsletter_subscribers;
DROP POLICY IF EXISTS "Admins manage subscribers" ON public.newsletter_subscribers;
CREATE POLICY "Admins manage subscribers" ON public.newsletter_subscribers
  FOR ALL TO authenticated USING (public.is_admin()) WITH CHECK (public.is_admin());

DROP POLICY IF EXISTS "Anyone can record content events" ON public.content_events;
CREATE POLICY "Anyone can record content events" ON public.content_events
  FOR INSERT TO anon, authenticated WITH CHECK (TRUE);
DROP POLICY IF EXISTS "Admins read content events" ON public.content_events;
CREATE POLICY "Admins read content events" ON public.content_events
  FOR SELECT TO authenticated USING (public.is_admin());

DROP POLICY IF EXISTS "Anyone can view featured skills" ON public.featured_skills;
CREATE POLICY "Anyone can view featured skills" ON public.featured_skills
  FOR SELECT TO anon, authenticated USING (TRUE);
DROP POLICY IF EXISTS "Admins manage featured skills" ON public.featured_skills;
CREATE POLICY "Admins manage featured skills" ON public.featured_skills
  FOR ALL TO authenticated USING (public.is_admin()) WITH CHECK (public.is_admin());

DROP POLICY IF EXISTS "Anyone can view ad placements" ON public.ad_placements;
CREATE POLICY "Anyone can view ad placements" ON public.ad_placements
  FOR SELECT TO anon, authenticated USING (TRUE);
DROP POLICY IF EXISTS "Admins manage ad placements" ON public.ad_placements;
CREATE POLICY "Admins manage ad placements" ON public.ad_placements
  FOR ALL TO authenticated USING (public.is_admin()) WITH CHECK (public.is_admin());

DROP POLICY IF EXISTS "Anyone can view public settings" ON public.site_settings;
CREATE POLICY "Anyone can view public settings" ON public.site_settings
  FOR SELECT TO anon, authenticated USING (is_public = TRUE);
DROP POLICY IF EXISTS "Admins manage settings" ON public.site_settings;
CREATE POLICY "Admins manage settings" ON public.site_settings
  FOR ALL TO authenticated USING (public.is_admin()) WITH CHECK (public.is_admin());

-- Allow admins to inspect account/profile information while retaining normal self-access.
DROP POLICY IF EXISTS "Admins can view profiles" ON public.profiles;
CREATE POLICY "Admins can view profiles" ON public.profiles
  FOR SELECT TO authenticated USING (public.is_admin());

-- Explicit API privileges. RLS still decides which rows each role may access.
GRANT SELECT, INSERT, UPDATE, DELETE ON public.saved_skills TO authenticated;
GRANT SELECT, UPDATE, DELETE ON public.newsletter_subscribers TO authenticated;
GRANT INSERT ON public.content_events TO anon, authenticated;
GRANT SELECT ON public.content_events TO authenticated;
GRANT SELECT ON public.featured_skills, public.ad_placements, public.site_settings TO anon, authenticated;
GRANT INSERT, UPDATE, DELETE ON public.featured_skills, public.ad_placements, public.site_settings TO authenticated;
GRANT USAGE, SELECT ON SEQUENCE public.content_events_id_seq TO anon, authenticated;

CREATE INDEX IF NOT EXISTS idx_newsletter_created_at ON public.newsletter_subscribers(created_at DESC);
CREATE INDEX IF NOT EXISTS idx_content_events_created_at ON public.content_events(created_at DESC);
CREATE INDEX IF NOT EXISTS idx_content_events_item ON public.content_events(item_type, item_slug);
CREATE INDEX IF NOT EXISTS idx_content_events_type ON public.content_events(event_type);
CREATE INDEX IF NOT EXISTS idx_featured_skills_active ON public.featured_skills(active, feature_type, display_order);

INSERT INTO public.ad_placements (placement_key, label, description)
VALUES
  ('homepage-inline', 'Homepage inline', 'Optional placement between homepage discovery sections.'),
  ('skill-inline', 'Skill guide inline', 'Placement inside long-form skill guides.'),
  ('career-inline', 'Career guide inline', 'Placement inside career profiles.'),
  ('blog-inline', 'Blog article inline', 'Placement inside long-form blog articles.')
ON CONFLICT (placement_key) DO NOTHING;

INSERT INTO public.site_settings (key, value, is_public)
VALUES ('marketing', '{"newsletterHeadline":"One useful skill every week","newsletterDescription":"Get practical skills, career ideas, and modern-work insights worth keeping."}'::jsonb, TRUE)
ON CONFLICT (key) DO NOTHING;

-- IMPORTANT: after creating your own account, make yourself an admin once in the SQL editor:
-- UPDATE public.profiles SET is_admin = TRUE WHERE email = 'you@example.com';
